version: "3"
services:
  source-1:
    image: node:latest
    container_name: source-1
    hostname: source-1
    ports:
      - 31200:31200
      - 31201:31201
      - 31202:31202
      - 9092:9092
    command: "/bin/bash -c /kafka.sh"
    environment:
      - "MISSION=source-1"
  source-2:
    image: node:latest
    container_name: source-2
    hostname: source-2
    ports:
      - 31210:31200
      - 31211:31201
      - 31212:31202
      - 9093:9092
    command: "/bin/bash -c /kafka.sh"
    environment:
      - "MISSION=source-2"
  source-3:
    image: node:latest
    container_name: source-3
    hostname: source-3
    ports:
      - 31220:31200
      - 31221:31201
      - 31222:31202
      - 9094:9092
    command: "/bin/bash -c /kafka.sh"
    environment:
      - "MISSION=source-3"
  node-main:
    image: node:latest
    container_name: node-main
    hostname: node-main
    depends_on:
      - source-1
      - source-2
      - source-3
    ports:
      - 8080:8080
      - 8081:8081
      - 7077:7077
    command: "/bin/bash -c /spark-main.sh"
    environment:
      - "MISSION=node-main"
      - "INIT_DAEMON_STEP=setup_spark"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "SPARK_MASTER_LOG=/spark/logs"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_WORKER_LOG=/spark/logs"
      - "SPARK_MASTER=spark://node-main:7077"
  node-worker-1:
    image: node:latest
    container_name: node-worker-1
    hostname: node-worker-1
    depends_on:
      - node-main
      - source-1
      - source-2
      - source-3
    ports:
      - 8082:8081
    command: "/bin/bash -c /spark-worker.sh"
    environment:
      - "MISSION=node-worker-1"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_WORKER_LOG=/spark/logs"
      - "SPARK_MASTER=spark://node-main:7077"
  node-worker-2:
    image: node:latest
    container_name: node-worker-2
    hostname: node-worker-2
    depends_on:
      - node-main
      - source-1
      - source-2
      - source-3
    ports:
      - 8083:8081
    command: "/bin/bash -c /spark-worker.sh"
    environment:
      - "MISSION=node-worker-2"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_WORKER_LOG=/spark/logs"
      - "SPARK_MASTER=spark://node-main:7077"

